### PR TITLE
Misc improvements

### PR DESCRIPTION
**Pull request by bosr**
Hi,

Here are several changes

# Misc improvements
Please be indulgent 😄, I'm a Vimscript newbie!
- filename change (fzy.vim)
- some refactoring / moving around of the functions (the reason why is in the notes section below)
- no bind keys by default
- add some API functions: quite a big name for just 2 functions 😂, namely `fzy#get_status_message` and `fzy#get_type_message`. This is for playing nice with plugins like lightline.
- add some limited ability to filter only buffer names (using the config below): it is limited because despite my efforts, I could not switch between filtering buffers and filtering files. You first have to toggle a switch using `<c-t>` and then re-call the plugin using `<c-p>`. *Please note that* the plugins opens for buffers first. You have to toggle and re-call the plugin to filter for files. Clearly not ideal.

# Config
My `init.vim` config for this plugin is:

    nnoremap <silent> <C-p> :FuzzyOpen<cr>
    let g:fuzzy_bindkeys = 1 " activate default bindkeys
    let g:fuzzy_contentsearch_engine = 'ag'

# Usage

    <C-P> opens the plugin in buffers mode
    <C-T> to toggle to files (this also kills, as <esc> does
    <C-P> opens the plugin in files mode
    <C-T> to toggle back to buffers

# Notes
1. I moved around the functions because they made more sense to me. Here is my vim window with the code now (thanks to folding). I hope it is self-explanatory
screen shot 2018-05-14 at 16 25 00

2. Should we submit all our common work back to the original author (Alexis)? I think it sounds better for the long run.

Thanks in advance for your comments and ideas.
Best regards

### CODE REVIEW

**Comment by bosr** [comment]
Here is a terminal recording
output

**Comment by nannery** [comment]
Awesome!!
1) I'm not particularly experienced in vimscript either, so give me a day or two to go over it and see if I understand the changes / they make sense
2) I definitely think we should submit back to the original author. I think it would be better to piecemeal out the changes as much as we can for clarity... possible through multiple merge requests to him

**Comment by bosr** [comment]
Cool ;)
As an alternative to multiple PR, we can make one PR using our current commits (each author will still be credited for his commits). Is ok with you?

**Comment by nannery** [comment]
yeah, that works!

**Comment by bosr** [comment]
Hi David, I opened the PR in the original repo. Cheers!

**Comment by bosr** [comment]
cleanup!

**Pull request closed without merging**
